version: '3.8'

services:
  question-service:
    build: ./question-service
    image: question-service:latest
    ports:
      - "8080:8080"  # Expose question service on port 8080
    volumes:
      - ./question-service:/usr/src/app  # For local development with live reloading
      - question_service_node_modules:/usr/src/app/node_modules  # Named volume for node_modules
    environment:
      - NODE_ENV=development  # Set environment to development

  user-service:
    build: ./user-service
    image: user-service:latest
    ports:
      - "3001:3001"  # Expose user service on port 8081
    volumes:
      - ./user-service:/usr/src/app  # For local development with live reloading
      - user_service_node_modules:/usr/src/app/node_modules  # Named volume for node_modules
    environment:
      - NODE_ENV=development  # Set environment to development

  frontend:
    build: ./frontend
    image: frontend:latest
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    depends_on:
      - question-service
      - user-service

volumes:
  question_service_node_modules:
  user_service_node_modules:
